/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.ide;

import fr.unice.polytech.idm.xtext.ide.AbstractSmartHomeDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmartHomeDSLIdeModule extends AbstractSmartHomeDSLIdeModule {
}
