/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartHomeDSLScopeProvider extends DelegatingScopeProvider {
}
