/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.ui;

import fr.unice.polytech.idm.xtext.ui.AbstractSmartHomeDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SmartHomeDSLUiModule extends AbstractSmartHomeDSLUiModule {
  public SmartHomeDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
