/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.idm.xtext.parser.antlr.internal.InternalSmartHomeDSLParser;
import fr.unice.polytech.idm.xtext.services.SmartHomeDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SmartHomeDSLParser extends AbstractAntlrParser {

	@Inject
	private SmartHomeDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartHomeDSLParser createParser(XtextTokenStream stream) {
		return new InternalSmartHomeDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmartHome";
	}

	public SmartHomeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartHomeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
