/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.serializer;

import com.google.inject.Inject;
import fr.unice.polytech.idm.xtext.services.SmartHomeDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import smartHome.Condition;
import smartHome.Duration;
import smartHome.Event;
import smartHome.Location;
import smartHome.Rule;
import smartHome.Sensor;
import smartHome.SensorType;
import smartHome.SmartHome;
import smartHome.SmartHomePackage;

@SuppressWarnings("all")
public class SmartHomeDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SmartHomeDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SmartHomePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SmartHomePackage.CONDITION:
				sequence_Condition(context, (Condition) semanticObject); 
				return; 
			case SmartHomePackage.DURATION:
				sequence_Duration(context, (Duration) semanticObject); 
				return; 
			case SmartHomePackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case SmartHomePackage.LOCATION:
				sequence_Location(context, (Location) semanticObject); 
				return; 
			case SmartHomePackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case SmartHomePackage.SENSOR:
				sequence_Sensor(context, (Sensor) semanticObject); 
				return; 
			case SmartHomePackage.SENSOR_TYPE:
				sequence_SensorType(context, (SensorType) semanticObject); 
				return; 
			case SmartHomePackage.SMART_HOME:
				sequence_SmartHome(context, (SmartHome) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Condition returns Condition
	 *
	 * Constraint:
	 *     (sensor=[Sensor|EString] operator=Operator operand=EInt)
	 */
	protected void sequence_Condition(ISerializationContext context, Condition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.CONDITION__SENSOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.CONDITION__SENSOR));
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.CONDITION__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.CONDITION__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.CONDITION__OPERAND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.CONDITION__OPERAND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConditionAccess().getSensorSensorEStringParserRuleCall_0_0_1(), semanticObject.eGet(SmartHomePackage.Literals.CONDITION__SENSOR, false));
		feeder.accept(grammarAccess.getConditionAccess().getOperatorOperatorEnumRuleCall_1_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getConditionAccess().getOperandEIntParserRuleCall_2_0(), semanticObject.getOperand());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Duration returns Duration
	 *
	 * Constraint:
	 *     (value=EInt unit=DurationUnit)
	 */
	protected void sequence_Duration(ISerializationContext context, Duration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.DURATION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.DURATION__VALUE));
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.DURATION__UNIT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.DURATION__UNIT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDurationAccess().getValueEIntParserRuleCall_0_0(), semanticObject.getValue());
		feeder.accept(grammarAccess.getDurationAccess().getUnitDurationUnitEnumRuleCall_1_0(), semanticObject.getUnit());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Event returns Event
	 *
	 * Constraint:
	 *     description=EString
	 */
	protected void sequence_Event(ISerializationContext context, Event semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.EVENT__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.EVENT__DESCRIPTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEventAccess().getDescriptionEStringParserRuleCall_0(), semanticObject.getDescription());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Location returns Location
	 *
	 * Constraint:
	 *     (name=EString (sensors+=Sensor sensors+=Sensor*)?)
	 */
	protected void sequence_Location(ISerializationContext context, Location semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (conditions+=Condition conditions+=Condition* duration=Duration event=Event)
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SensorType returns SensorType
	 *
	 * Constraint:
	 *     name=EString?
	 */
	protected void sequence_SensorType(ISerializationContext context, SensorType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Sensor returns Sensor
	 *
	 * Constraint:
	 *     (name=EString sensorType=[SensorType|EString] dataFile=EString)
	 */
	protected void sequence_Sensor(ISerializationContext context, Sensor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.SENSOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.SENSOR__NAME));
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.SENSOR__SENSOR_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.SENSOR__SENSOR_TYPE));
			if (transientValues.isValueTransient(semanticObject, SmartHomePackage.Literals.SENSOR__DATA_FILE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SmartHomePackage.Literals.SENSOR__DATA_FILE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSensorAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getSensorAccess().getSensorTypeSensorTypeEStringParserRuleCall_2_0_1(), semanticObject.eGet(SmartHomePackage.Literals.SENSOR__SENSOR_TYPE, false));
		feeder.accept(grammarAccess.getSensorAccess().getDataFileEStringParserRuleCall_4_0(), semanticObject.getDataFile());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SmartHome returns SmartHome
	 *
	 * Constraint:
	 *     (
	 *         sensorTypes+=SensorType 
	 *         sensorTypes+=SensorType* 
	 *         locations+=Location 
	 *         locations+=Location* 
	 *         rules+=Rule 
	 *         rules+=Rule*
	 *     )
	 */
	protected void sequence_SmartHome(ISerializationContext context, SmartHome semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
