/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.ui.contentassist;

import fr.unice.polytech.idm.xtext.ui.contentassist.AbstractSmartHomeDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SmartHomeDSLProposalProvider extends AbstractSmartHomeDSLProposalProvider {
}
