/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext;

import fr.unice.polytech.idm.xtext.SmartHomeDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeDSLStandaloneSetup extends SmartHomeDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new SmartHomeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
