/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext;

import fr.unice.polytech.idm.xtext.AbstractSmartHomeDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmartHomeDSLRuntimeModule extends AbstractSmartHomeDSLRuntimeModule {
}
